"""Strict Pydantic IR models for SPARQL query plans.

The mutually-recursive types — expressions, patterns, and plans — are
defined together in :mod:`graph_mcp.models._ir`. The submodules
:mod:`expressions`, :mod:`patterns`, and :mod:`query_plan` are thin
re-export shims that exist for naming readability; they do not run any
``model_rebuild`` machinery.
"""

from graph_mcp.models._ir import (
    ALLOWED_AGGREGATES,
    ALLOWED_BINARY_OPS,
    ALLOWED_DATETIME_ACCESSORS,
    ALLOWED_FUNCTIONS,
    ALLOWED_UNARY_OPS,
    AggregateExpr,
    AskPlan,
    BinaryExpr,
    BindPattern,
    BoundExpr,
    ConstructPlan,
    DateTimeExpr,
    ExistsExpr,
    Expression,
    FilterPattern,
    FunctionExpr,
    GraphPattern,
    GroupPattern,
    InExpr,
    LangMatchesExpr,
    MinusPattern,
    NotExistsExpr,
    NotExpr,
    OptionalPattern,
    OrderClause,
    Pattern,
    Projection,
    PropertyPath,
    PropertyPathAlt,
    PropertyPathInverse,
    PropertyPathOneOrMore,
    PropertyPathSeq,
    PropertyPathTerm,
    PropertyPathZeroOrMore,
    PropertyPathZeroOrOne,
    QueryPlan,
    RegexExpr,
    SelectPlan,
    ServicePattern,
    SubqueryPattern,
    TriplePattern,
    UnaryExpr,
    UnionPattern,
    ValuesPattern,
)
from graph_mcp.models.iri import (
    Iri,
    LiteralValue,
    Prefix,
    PrefixedName,
    RdfTerm,
    Var,
)
from graph_mcp.models.literals import (
    DEFAULT_PREFIXES,
    LANG_TAG_REGEX,
    PREFIX_REGEX,
    VAR_NAME_REGEX,
)
from graph_mcp.models.results import (
    AskResult,
    BindingValue,
    ConstructResult,
    QueryExecutionMetadata,
    QueryResult,
    SelectResult,
    SolutionRow,
    Triple,
)
from graph_mcp.models.validation import ValidationIssue, ValidationResult

__all__ = [
    "ALLOWED_AGGREGATES",
    "ALLOWED_BINARY_OPS",
    "ALLOWED_DATETIME_ACCESSORS",
    "ALLOWED_FUNCTIONS",
    "ALLOWED_UNARY_OPS",
    "DEFAULT_PREFIXES",
    "LANG_TAG_REGEX",
    "PREFIX_REGEX",
    "VAR_NAME_REGEX",
    "AggregateExpr",
    "AskPlan",
    "AskResult",
    "BinaryExpr",
    "BindPattern",
    "BindingValue",
    "BoundExpr",
    "ConstructPlan",
    "ConstructResult",
    "DateTimeExpr",
    "ExistsExpr",
    "Expression",
    "FilterPattern",
    "FunctionExpr",
    "GraphPattern",
    "GroupPattern",
    "InExpr",
    "Iri",
    "LangMatchesExpr",
    "LiteralValue",
    "MinusPattern",
    "NotExistsExpr",
    "NotExpr",
    "OptionalPattern",
    "OrderClause",
    "Pattern",
    "Prefix",
    "PrefixedName",
    "Projection",
    "PropertyPath",
    "PropertyPathAlt",
    "PropertyPathInverse",
    "PropertyPathOneOrMore",
    "PropertyPathSeq",
    "PropertyPathTerm",
    "PropertyPathZeroOrMore",
    "PropertyPathZeroOrOne",
    "QueryExecutionMetadata",
    "QueryPlan",
    "QueryResult",
    "RdfTerm",
    "RegexExpr",
    "SelectPlan",
    "SelectResult",
    "ServicePattern",
    "SolutionRow",
    "SubqueryPattern",
    "Triple",
    "TriplePattern",
    "UnaryExpr",
    "UnionPattern",
    "ValidationIssue",
    "ValidationResult",
    "ValuesPattern",
    "Var",
]
